ALTER TABLE "users"
ADD COLUMN "avatar_url" TEXT,
ADD COLUMN "bio" VARCHAR(255),
ADD COLUMN "open_to_work" BOOL DEFAULT FALSE,
ADD COLUMN "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "deleted_at" TIMESTAMP;

CREATE INDEX idx_users_bio ON "users" ("bio");