// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
)

type User struct {
	ID            int64
	Email         string
	Password      sql.NullString
	FullName      string
	VerifiedEmail sql.NullBool
}

type UserOtp struct {
	ID     int64
	UserID sql.NullInt64
	Otp    sql.NullString
}
