// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package posts

import (
	"context"
	"database/sql"
)

const insertReportedPost = `-- name: InsertReportedPost :one
INSERT INTO reported_posts
(user_id, post_id, reason, message)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, post_id, reason, message
`

type InsertReportedPostParams struct {
	UserID  sql.NullInt64
	PostID  sql.NullInt64
	Reason  sql.NullString
	Message sql.NullString
}

func (q *Queries) InsertReportedPost(ctx context.Context, arg InsertReportedPostParams) (ReportedPost, error) {
	row := q.db.QueryRowContext(ctx, insertReportedPost,
		arg.UserID,
		arg.PostID,
		arg.Reason,
		arg.Message,
	)
	var i ReportedPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Reason,
		&i.Message,
	)
	return i, err
}
